[package]
name = "inquir"
authors = ["Ryo Wakizaka <ryo.wakizaka516@gmail.com>"]
description = "The InQuIR programming language"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
nom = "7"
thiserror = "1.0"
